CREATE TABLE IF NOT EXISTS BORROWER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    isbn VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    borrower_id BIGINT,
    CONSTRAINT fk_borrower
        FOREIGN KEY (borrower_id) 
        REFERENCES BORROWER(id)
);
